name: Run Test Suite
on: push

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest repo
        uses: actions/checkout@master
      - name: Build Dev Docker Image
        run: docker build -t jackmckew/docker-react -f Dockerfile.dev .
      - name: Run test suite
        run: docker run -e CI=true jackmckew/docker-react npm run test -- --coverage
