name: Run Test Suite
on: push

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@master

      - name: Build Dev Docker Image
        run: docker build -t jackmckew/docker-react -f Dockerfile.dev .

      - name: Run Test Suite
        run: docker run -e CI=true jackmckew/docker-react npm run test -- --coverage

      - name: Generate Deployment Package
        run: zip deploy.zip build

      - name: Deploy to AWS ElasticBeanstalk
        if: success()
        uses: einaregilsson/beanstalk-deploy@v10
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: docker-react
          environment_name: DockerReact-env
          version_label: 0.1.0
          region: us-east-2
          deployment_package: deploy.zip
